services:
  postgres_db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: astaroth639
      POSTGRES_DB: ventaSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ventaSQL"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:  
    build:
      context: ./VentasSql
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/ventaSQL
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: astaroth639
        SPRING_JPA_HIBERNATE_DDL_AUTO: validate

  frontend:
    environment:
    - NODE_ENV=production
    build:
      context: ./app-ventas
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: